### ISSUE TITLE
Quotes required for boolean docker-compose setting

### ISSUE THREAD

**Issue by david--smith** [confluentinc/bottledwater-pg#100]
After fetching the latest, the Docker initiation failed with:
```
bottledwater.environment.BOTTLED_WATER_ALLOW_UNKEYED contains true, which is an invalid type, it should be a string, number, or a null`.
```
Works by changing the `true` value from:

```yaml
    BOTTLED_WATER_ALLOW_UNKEYED: true
```

to:

```yaml
    BOTTLED_WATER_ALLOW_UNKEYED: "true"
```

**Comment by samstokes** [comment]
Thanks for this report!  I've pushed 5531929 which should fix this.

Out of interest, what version of Docker Compose are you running?  (`docker-compose --version`)  I can't reproduce this on my dev machine, which is running (the rather old) Docker Compose 1.4.2.
