### ISSUE TITLE
Allow initial snapshot to be skipped

### ISSUE THREAD

**Issue by kinghuang** [confluentinc/bottledwater-pg#112]
It would be useful to have an option to skip the initial snapshot. In the case where the database tables contain log and event records and I am able to configure Bottled Water for inserts and updates (see #111), I might not care for a snapshot of existing rows representing past data (related to #110). In this case, I'd like Bottled Water to just send new rows to Kafka.

**Comment by samstokes** [comment]
I added a `--skip-snapshot` flag recently that does exactly this :) See #103.

**Comment by kinghuang** [comment]
Awesome, @samstokes! I guess I should read through the recent PRs to catch new goodies. 👍
