### ISSUE TITLE
Sending full rows vs just filed update

### ISSUE THREAD

**Issue by eugenemiretsky** [confluentinc/bottledwater-pg#12]
Thanks for the great work! 

Just trying to gain a better understanding of some of your design decisions - If I have a big user table, and the name field changes, you are writing the whole row to Kafka. Alternatively, you could just write the modified field (I think that's what Oracle Golden Gate does)
I suppose this enables using Kafka compaction, but at the same time it 
(a) Introduces a performance penalty as I would imagine that you need to query the database to get the full row
(b) Increases the size of data being transferred and later processed
(c) Discards some information about the nature of the transaction (I might want to know that a specific field in the table changes, as oppose to any field)

**Comment by ept** [comment]
Yes, Bottled Water writes the entire new row to Kafka. As far as I know, Postgres itself also writes an entire row at a time (apart from TOAST if you have large variable-length fields) so this shouldn't introduce a performance penalty in most cases. It may be possible to capture only changes, but it would make life significantly harder for downstream consumers, since they would have to combine several rows into one.

Capturing before/after changes to a row would actually be *more* expensive, since it requires logging changes with `REPLICA IDENTITY FULL`. The default logging level for tables only logs the new value of the row, not the old one.

**Comment by wushujames** [comment]
Martin, are you saying that Postgres only writes the new row's data to the WAL that Bottled Water listens to?

What if the UPDATE statement modifies the row's primary key? In that case, you want to emit to Kafka a delete of the previous row, and then emit the new row with the new primary key.

If you don't do that, then your Kafka topic might contain a record which does not exist in Postgres. Namely, postgres will have the new row, and Kafka will have both the old row (with old primary) as well as the new row.

It's possible that Postgres might automatically generate a delete as well as a write, if the primary key for a row changes, but it's something you should check.

**Comment by ept** [comment]
@wushujames Good point! I wasn't correctly handling the case where an UPDATE modifies a row's primary key. I just fixed that in #14, by turning it into a delete of the old key, and an insert of the new key.

In the default logging mode (`REPLICA IDENTITY DEFAULT`), Postgres only logs the new row, not the old row — except (as I found yesterday) in the case where the primary key is modified. In that case it will also log the columns from the old row that constitute the primary key. Even in this case, it doesn't log the entire old row — the columns that are not part of the key are nulled out.

The mode `REPLICA IDENTITY USING INDEX <foo>` behaves the same as `REPLICA IDENTITY DEFAULT`. The only mode that logs the entire old row is `REPLICA IDENTITY FULL`.

Thanks James for pointing that out.

**Comment by wushujames** [comment]
I just saw your commit. Super cool. Glad to help!

**Comment by ruimarinho** [comment]
@ept what would be the best way to broadcast the diff in your opinion? Generate it on the consumer or include a diff when publishing, assuming bottled water has access to the previous and current rows?

**Comment by ept** [comment]
@ruimarinho See my comment on #54.
