### ISSUE TITLE
Does set-returning-function interface actually stream the results?

### ISSUE THREAD

**Issue by a1exsh** [confluentinc/bottledwater-pg#19]
Hi,

I've tried using `bottledwater_export()` on something bigger than trivial testing table and what I see is that though the C function itself is called/returns once per table row, the intermediate results are still accumulated in postgres completely, before it starts to send them to the client.

I'm testing on a table like this one: `CREATE TABLE huge1 AS SELECT * FROM generate_series(1, 1000000)` (a Million rows).

Did you manage to actually make use of it on large scale?

I've tracked the issue down to `ExecMakeTableFunctionResult()` in core, which is accumulating the results before returning even the first row, but I don't see yet if this behavior can be mitigated.  Should we bring it up on pgsql-hackers, probably?

Thank you.
Alex

**Comment by ept** [comment]
Hi Alex, admittedly I never tested it on a big table, I just went by the docs. :flushed: If you want to bring it up on pgsql-hackers, that would be great. Thanks!

**Comment by ept** [comment]
Just had a thought: the BW client currently does `SELECT bottledwater_export()`, but perhaps it would be different if it did `SELECT * FROM bottledwater_export()`. Have you tried that?

**Comment by a1exsh** [comment]
Tried, not really different. I think there was a note in the docs around
CREATE FUNCTION ... RETURNS SETOF, that it does accumulate the result set,
but that looks like implementation detail, not some fundamental limitation.

**Comment by a1exsh** [comment]
On Sun, Jun 21, 2015 at 3:05 PM, Alex Shulgin <alex.shulgin@gmail.com>
wrote:

> Tried, not really different. I think there was a note in the docs around
> CREATE FUNCTION ... RETURNS SETOF, that it does accumulate the result set,
> but that looks like implementation detail, not some fundamental limitation.
>
Actually, looks like this section on RETURN NEXT in PL/PgSQL is relevant:
http://www.postgresql.org/docs/9.4/static/plpgsql-control-structures.html#AEN60519
(see note in the end)

The most relevant discussion on hackers I could find is this one:
http://www.postgresql.org/message-id/1242582655.18964.33.camel@guedes-laptop

Maybe it has something to do with "SELECT func()" vs. "SELECT * FROM
func()" indeed, but I didn't see a difference when testing this on that
huge table.

--
Alex

**Comment by a1exsh** [comment]
So what I've found is that actually the root cause is improper use of memory contexts in the export function.  Please see the fix: https://github.com/confluentinc/bottledwater-pg/pull/20

And you really want to keep "SELECT bottledwater_export()", i.e. without "SELECT * FROM", because that variant indeed accumulates the whole result set on the server side, it's just that this was not the root cause of the out-of-memory condition in my test.

Cheers!
Alex

**Comment by ept** [comment]
Closing, fixed by #20. Thanks!
