### ISSUE TITLE
Error parsing frame data: Cannot save record schema

### ISSUE THREAD

**Issue by bmorton** [confluentinc/bottledwater-pg#26]
I'm getting this error from the bottledwater client whenever a record exists in my table.  If I start the client with data in the table, it exits with this error:

```
Created replication slot "bottledwater", capturing consistent snapshot "00001C63-1".
INFO:  bottledwater_export: Table public.message_threads is keyed by index message_threads_pkey
INFO:  bottledwater_export: Table public.messages is keyed by index messages_pkey
/usr/local/bin/bottledwater: Error parsing frame data: Cannot save record schema
Dropping replication slot since the snapshot did not complete successfully.
```

If I start the client with an empty table and only a structure, the client loads fine, but as soon as I add a record to a table that its replicating, the client exists with:

```
/usr/local/bin/bottledwater: Error parsing frame data: Cannot save record schema
```

Is there anything else I can do to debug this further?  The application layer that connects to the database is a Rails app and the schema is all managed through Rails migrations, if that is at all useful.

**Comment by bmorton** [comment]
This is what one of the tables that bombs out looks like, as provided by pg_dump, excluding indexes:

```sql
CREATE TABLE message_threads (
    id bigint NOT NULL,
    something_id bigint,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    somethings_count bigint,
    has_something boolean DEFAULT false,
    something_two_count bigint,
    in_something boolean DEFAULT false NOT NULL
);

CREATE SEQUENCE message_threads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE message_threads_id_seq OWNED BY message_threads.id;
ALTER TABLE ONLY message_threads ALTER COLUMN id SET DEFAULT nextval('message_threads_id_seq'::regclass);
ALTER TABLE ONLY message_threads ADD CONSTRAINT message_threads_pkey PRIMARY KEY (id);
```

**Comment by ept** [comment]
Thanks for reporting this. I think it's a duplicate of #18, an open bug.

**Comment by bmorton** [comment]
Thanks!  I'll close this one out then unless I can determine that this is somehow different.  I'm gonna try to start digging into #18 and see how far I can get.
