### ISSUE TITLE
Error on make && make install on redhat 6

### ISSUE THREAD

**Issue by jimzzhou** [confluentinc/bottledwater-pg#28]
[root@deweystorm06 bottledwater]# make clean
make -C ext clean
make[1]: Entering directory `/root/bottledwater/ext'
rm -f bottledwater.so   libbottledwater.a
rm -f io_util.o logdecoder.o oid2avro.o protocol.o protocol_server.o snapshot.o
make[1]: Leaving directory `/root/bottledwater/ext'
make -C client clean
make[1]: Entering directory `/root/bottledwater/client'
rm -f replication.o protocol.o protocol_client.o connect.o bwtest.o bwtest libbottledwater.a
make[1]: Leaving directory `/root/bottledwater/client'
make -C kafka clean
make[1]: Entering directory `/root/bottledwater/kafka'
rm -f bottledwater.o registry.o bottledwater
make[1]: Leaving directory `/root/bottledwater/kafka'
[root@deweystorm06 bottledwater]# make
make -C ext all
make[1]: Entering directory `/root/bottledwater/ext'
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -fno-strict-aliasing -fwrapv -fpic -I/usr/local/include   -std=c99 -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o io_util.o io_util.c
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -fno-strict-aliasing -fwrapv -fpic -I/usr/local/include   -std=c99 -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o logdecoder.o logdecoder.c
In file included from logdecoder.c:2:
protocol_server.h:6:39: error: replication/output_plugin.h: No such file or directory
In file included from logdecoder.c:2:
protocol_server.h:17: error: expected specifier-qualifier-list before ‘Form_pg_index’
protocol_server.h:29: error: expected declaration specifiers or ‘...’ before ‘ReorderBufferTXN’
protocol_server.h:30: error: expected declaration specifiers or ‘...’ before ‘ReorderBufferTXN’
protocol_server.h:30: error: expected declaration specifiers or ‘...’ before ‘XLogRecPtr’
protocol_server.h:31: error: expected declaration specifiers or ‘...’ before ‘Relation’
protocol_server.h:31: error: expected declaration specifiers or ‘...’ before ‘TupleDesc’
protocol_server.h:31: error: expected declaration specifiers or ‘...’ before ‘HeapTuple’
In file included from logdecoder.c:2:
protocol_server.h:32: error: expected declaration specifiers or ‘...’ before ‘Relation’
protocol_server.h:32: error: expected declaration specifiers or ‘...’ before ‘HeapTuple’
protocol_server.h:32: error: expected declaration specifiers or ‘...’ before ‘HeapTuple’
protocol_server.h:33: error: expected declaration specifiers or ‘...’ before ‘Relation’
protocol_server.h:33: error: expected declaration specifiers or ‘...’ before ‘HeapTuple’
protocol_server.h:37: error: expected ‘)’ before ‘rel’
logdecoder.c:5:33: error: replication/logical.h: No such file or directory
logdecoder.c:11: error: expected ‘)’ before ‘*’ token
logdecoder.c:13: error: expected ‘)’ before ‘*’ token
logdecoder.c:14: error: expected ‘)’ before ‘*’ token
logdecoder.c:15: error: expected ‘)’ before ‘*’ token
logdecoder.c:16: error: expected ‘)’ before ‘*’ token
logdecoder.c:17: error: expected ‘)’ before ‘*’ token
logdecoder.c:28: error: expected ‘)’ before ‘*’ token
logdecoder.c:34: error: expected ‘)’ before ‘*’ token
logdecoder.c:43: error: expected ‘)’ before ‘*’ token
logdecoder.c:58: error: expected ‘)’ before ‘*’ token
logdecoder.c:68: error: expected ‘)’ before ‘*’ token
logdecoder.c:84: error: expected ‘)’ before ‘*’ token
logdecoder.c:101: error: expected ‘)’ before ‘*’ token
logdecoder.c:159: error: expected ‘)’ before ‘*’ token
make[1]: *** [logdecoder.o] Error 1
make[1]: Leaving directory `/root/bottledwater/ext'
make: *** [all] Error 2
[root@deweystorm06 bottledwater]#

**Comment by ept** [comment]
@jimzzhou Which version of Postgres do you have installed? It looks like the file `/usr/include/pgsql/server/replication/output_plugin.h` is missing on your system. That file should be included in Postgres 9.4 and above (provided that you have the development package installed).

**Comment by samstokes** [comment]
I'm going to close this issue since it's been nearly a year since it was first reported, and a lot of changes have been made to the build process since then.  Please feel free to file another issue if you're still having problems building from the latest master.
