### ISSUE TITLE
librdkafka dependency vagueness -- version 0.8.6 actually required

### ISSUE THREAD

**Issue by petergeoghegan** [confluentinc/bottledwater-pg#29]
The documentation is not sufficiently clear on build dependencies. It should state that version 0.8.6 of librdkafka is required. The version available from Ubuntu 14.04 LTS produces one linker error.

I only figured this out by grepping, and noticing that build/Dockerfile.client requires this version specifically. I had to use the "0.8.6" tag from git to successfully build bottledwater.

**Comment by gonzalo-bulnes** [comment]
Hi @petergeoghegan,

I'm building Bottled Water from source on Ubuntu Trusty.

As far as I've seen, **0.8.5** (from the [Ubuntu Vivid universe repository](http://packages.ubuntu.com/vivid/librdkafka-dev)) allows to build Bottled Water successfully by solving the following error, and I think **0.8.4** [should work just fine](https://github.com/gonzalo-bulnes/bottledwater-pg/commit/f45da43a7d21ea78019814fb830c38a1c619d5fd):

```bash
[...]
gcc bottledwater.o registry.o ../client/libbottledwater.a -o bottledwater -L/usr/lib/x86_64-linux-gnu -lpq -lrdkafka -lz -lpthread  -L/usr/local/lib -lavro -lz -lsnappy   -L/usr/lib/x86_64-linux-gnu -lcurl -ljansson  
bottledwater.o: In function `init_producer':
bottledwater.c:(.text+0xfa4): undefined reference to `rd_kafka_conf_set_dr_msg_cb'
collect2: error: ld returned 1 exit status
make[1]: *** [bottledwater] Error 1
make[1]: Leaving directory `/home/gonzalo/dev/bottledwater-pg/kafka'
make: *** [all] Error 2
```

Was that the error you ran into? I opened a PR to update the documentation accordingly (see #30).

**Comment by petergeoghegan** [comment]
Yes. That was the error. Thanks.

**Comment by gonzalo-bulnes** [comment]
Thak you for you feedback @petergeoghegan!
@ept I think you can close this issue, #30 was meant to solve it.

**Comment by ept** [comment]
Great, thanks both for your help! Closing this.
