### ISSUE TITLE
Ability to filter on certain tables

### ISSUE THREAD

**Issue by gsogol** [confluentinc/bottledwater-pg#42]
An ability to export data based on predefined filters belonging to certain tables and columns would be helpful to remove unnecessary noise. For example, only send data to kafka when table X, column Y gets modified. Even better approach would be able to specify when column Y of table X gets data inserted (not updated or deleted).

**Comment by ept** [comment]
Good idea. We're already tracking this under #21, so I'll close this as duplicate. Would be great if you want to contribute a patch.
