### ISSUE TITLE
Loading the extension in posgresql 9.5

### ISSUE THREAD

**Issue by timyguo** [confluentinc/bottledwater-pg#44]
Hi,

I am attempting the build from source route and I have encountered the following error when I tried to load the extension in postgres

```
create extension bottledwater;
ERROR:  could not load library "/usr/lib/postgresql/9.5/lib/bottledwater.so": /usr/lib/postgresql/9.5/lib/bottledwater.so: undefined symbol: oid_hash
```

Any advice on what to do next?

**Comment by timyguo** [comment]
The problem is gone once i switched back to 9.4

**Comment by ept** [comment]
Thanks @timyguo for reporting this. We should make Bottled Water work in Postgres 9.5 as well, so I'll reopen this issue.

**Comment by devinrsmith** [comment]
+1
