### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by samstokes** [confluentinc/bottledwater-pg#51]
Bottled Water should have a continuous integration build so we have centralised, automated checks that:

 * master always builds
 * the Dockerfile always builds (to catch things like #48)
 * pull requests merge and build cleanly against the latest master

This would also let us do things like:

 * run the automated test suite, once we have one :) (#3)
 * build distribution packages (#6)
 * test against various versions of our dependencies (e.g. libpq-dev, librdkafka) to catch regressions and incompatibilities.

**Comment by samstokes** [comment]
I've just merged PR #72 which added a test suite and Travis configuration for Bottled Water.  The Travis setup builds Bottled Water (as well as Avro, librdkafka etc) via Docker, then runs the test suite against the built Docker images.  It should be relatively straightforward to extend it to build distribution packages, or run against different dependency versions.

I don't have admin rights to this repo, so I can't turn on Travis builds of confluentinc/master.  Could I interest somebody with admin rights in doing that?  /cc @ept @ewencp @gwenshap  Turning on the Travis build can be done on [Confluent's Travis profile page](https://travis-ci.org/profile/confluentinc); that should also enable us to use Travis to validate pull requests going forward.

**Comment by ept** [comment]
@samstokes I think I just gave you admin rights, can you try now?

**Comment by samstokes** [comment]
Epic, thanks @ept !  I've enabled the Travis build, so subsequent PRs and pushes to master should get automatically tested.
