### ISSUE TITLE
Security: How to hide postgresql user and password from ps output ?

### ISSUE THREAD

**Issue by abcfy2** [confluentinc/bottledwater-pg#90]
For security reason, user and password should not show in the processes list.

Would bottledwater support [libpg environment](https://www.postgresql.org/docs/current/static/libpq-envars.html) ? So that it can store user and password in environment variables. Or other ways like the behavior of `mysql -u$user -p$password` ?

**Comment by ept** [comment]
@abcfy2 The Bottled Water client uses libpq, so passing the user and password in environment variables should work. Please let us know if it doesn't work.

**Comment by abcfy2** [comment]
Oh yes, it works. Because I use the wrong postgres URI string.

```bash
export PGUSER="my_user"
export PGPASSWORD="mypass"
export PGHOST="127.0.0.1"
export PGPORT="5432"
export PGDATABASE="mydb"

$ psql                                        # <====== work
$ bottledwater -d "postgres://"  # <========= This is the correct way.
```
