### ISSUE TITLE
Dockerfile image build expect user interaction

### ISSUE THREAD

**Issue by juliaaano** [confluentinc/bottledwater-pg#92]
During build of _Dockerfile.client_ image, a user interaction is expected. See extract of sysout: 
```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring postgresql-common
-----------------------------

A new version (/tmp/postgresql-common.Vnc3kp) of configuration file
/etc/postgresql-common/createcluster.conf is available, but the version
installed currently has been locally modified.

  1. install the package maintainer's version
  2. keep the local version currently installed
  3. show the differences between the versions
  4. show a side-by-side difference between the versions
  5. show a 3-way difference between available versions
  6. do a 3-way merge between available versions (experimental)
  7. start a new shell to examine the situation

What do you want to do about modified configuration file createcluster.conf?
```
As you can see in the first log statements, _dialog frontend is not usable_.
I suggest adding **DEBIAN_FRONTEND=noninteractive** before _apt-get upgrade_ statement present in the corresponding docker image file.

**Comment by juliaaano** [comment]
@samstokes I have a pull request ready, but no permission to push. Let me know if you have interest on me submitting.

**Comment by samstokes** [comment]
Hi @juliaaano, thanks for this report!  Looks like the Travis build also can reproduce this problem (e.g. https://travis-ci.org/confluentinc/bottledwater-pg/builds/143137836) - something must have changed with the upstream Docker images.  I'm not quite sure why that file createcluster.conf is getting locally modified.

Do you find that setting `DEBIAN_FRONTEND=noninteractive` fixes the build?  I'd be happy to accept a pull request that adds that.

I'm not sure what you mean by "no permission to push" - although you won't be able to push directly to the confluentinc repo, if you make your own fork of bottledwater-pg you should be able to [submit a pull request](https://github.com/confluentinc/bottledwater-pg/compare) against the confluentinc repo without needing any special permissions.  If I'm misunderstanding the problem, please let me know and I can help figure it out!

**Comment by juliaaano** [comment]
Dear @samstokes, I appreciate for being so receptive and patient on explaining. I've submitted pull request #94 and the build passed. Let me know if I missed something. Thank you.
